port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
cfw-bypass:
  - qq.com
  - music.163.com
  - "*.music.126.net"
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 5000

# 代理节点
proxies: ~

# 代理组策略
proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - ✈ 延迟最低
      - ✈ 手动选择
      - ✈ 故障切换
      - DIRECT
      - "1"
  - name: 广告拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: final
    type: select
    proxies:
      - 节点选择
      - ✈ 手动选择
      - ✈ 延迟最低
      - ✈ 故障切换
      - DIRECT
  - name: ✈ 手动选择
    type: select
    proxies:
      - "1"
  - url: http://www.gstatic.com/generate_204
    interval: 500
    name: ✈ 延迟最低
    type: url-test
    proxies:
      - "1"
  - url: http://www.gstatic.com/generate_204
    interval: 500
    name: ✈ 故障切换
    type: fallback
    proxies:
      - "1"

# 规则
rules:
# %%s将被替换为acl路由规则
%s

  # GeoIP China
  - GEOIP,CN,DIRECT

  # 自定义
  - DOMAIN-KEYWORD,duandada,DIRECT

  - MATCH,final
