port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090


# 代理节点
proxies: ~

# 代理策略组
# - "1"：表示该策略组会写入解析出来节点信息
proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - ✈ 延迟最低
      - ✈ 手动选择
      - ✈ 故障切换
      - DIRECT
      - "1"
  - name: 广告拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: final
    type: select
    proxies:
      - 节点选择
      - ✈ 手动选择
      - ✈ 延迟最低
      - ✈ 故障切换
      - DIRECT
  - name: ✈ 手动选择
    type: select
    proxies:
      - "1"
  - url: http://www.gstatic.com/generate_204
    interval: 500
    name: ✈ 延迟最低
    type: url-test
    proxies:
      - "1"
  - url: http://www.gstatic.com/generate_204
    interval: 500
    name: ✈ 故障切换
    type: fallback
    proxies:
      - "1"

# 规则
rules:
{{.}}

  # GeoIP China
  - GEOIP,CN,DIRECT

  # 自定义
  # - DOMAIN-KEYWORD,site.com,DIRECT

  - MATCH,final
